# Configuration du serveur
server:
  port: 8080
  base_url: "http://localhost:8080"

# Configuration de la base de données
database:
  name: "url_shortener.db"

# Configuration des analytics
analytics:
  buffer_size: 1000
  worker_count: 5

# Configuration du moniteur
monitor:
  interval_minutes: 5